### ISSUE TITLE
add https://github.com/redis/rueidis

### ISSUE THREAD

**Issue by vincentserpoul** [ammario/redjet#1]
I think it would be nice to add https://github.com/redis/rueidis in your benchmarks, as it is also another competitor in the go redis ecosystem.

**Comment by ammario** [comment]
Done here: 3fbd3afe97e64edbe1ba6f3579e46a1b620ff39c.

**Comment by rueian** [comment]
Hi @ammario,

Thank you for adding a benchmark comparison with Rueidis.

However, the way how you benchmark them looks weird to me. Is there any reason not to put full operation inside the loop of `b.N`? That should be the normal way how to work with the Go benchmark system.

For example, instead of this:
https://github.com/ammario/redjet/blob/d83319d0b6dbc6922ea0166839ed7c7704e46cd4/bench/get_test.go#L89-L106

It should be typically this:
```go
func (c *redjetClient) get(b *testing.B, ctx context.Context, payload string, n int) {
	err := c.Command(ctx, "SET", "foo", payload).Ok()
	require.NoError(b, err)

	for i := 0; i < b.N; i++ {
		var r *redjet.Result
		for j := 0; j < n; j++ {
			r = c.Pipeline(ctx, r, "GET", "foo")
		}
		for r.Next() {
			read, err := r.WriteTo(io.Discard)
			require.NoError(b, err)
			if read != int64(len(payload)) {
				b.Fatalf("read %d bytes, expected %d", read, len(payload))
			}
		}	
	}
}
```

**Comment by ammario** [comment]
That `n` variable is actually unused (eb5fa82a07d8e11143ad55037e98cd521dfa7921). The reason to batch everything into a pipeline of size `b.N` is outlined [here](https://redis.io/docs/management/optimization/benchmarks/#pitfalls-and-misconceptions). We really want to benchmark the protocol handling and not IPC.

Also, the second `for r.Next()` loop will go `b.N` times, since it consumes a response for each command.

**Comment by rueian** [comment]
Hi @ammario, thank you for your explanation. That makes sense, but you would need to explicitly assign `b.N` to a fixed value by the `-benchtime` flag, such as `-benchtime=1000x`, or you were benchmarking different workloads on these clients.

BTW, would you also be interested in improving rueidis?

**Comment by ammario** [comment]
@rueian that's fair. I'm taking it for granted that `b.N` will get sufficiently large but it would be better to hard-code benchtime into the benchmarks.

> BTW, would you also be interested in improving rueidis?

Would love to check it out at some point. I made this package during my long weekend where I had an abundance of time, so no promises on that happening soon :)
